/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

	uint8_t banda = 0;
	uint8_t banda1 = 0;
	uint8_t banda3 = 0;
	uint8_t fila1 = 0;
	uint8_t fila2 = 0;
	uint8_t fila3 = 0;
	uint8_t fila4 = 0;
	uint8_t fila5 = 0;
	uint8_t fila6 = 0;
	uint8_t fila7 = 0;
	uint8_t fila8 = 0;

int main(void) {

	fila1 = 77;
	fila2 = (0xAC & 0xDC) >> 0x2;
	fila3 = (uint8_t) (((!!0xB) << 0b0100)| (~0x97));
	fila4 = (uint8_t) (0xCAFE & 0xC0C0) >> 8;
	//3min 25s = 60*3 + 25 = 205
	fila5 = (uint8_t) 205;
	fila6 = 21*4;
	fila7 = (uint8_t) 73 | 70;
	fila8 = 24;






	/* Loop forever */
	while (1) {

		}

	}
