/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define RCC_BASE_ADDRESS
#define RCC_AHB1ENR_OFFSET
#define RCC_AHB1ENR

unsigned int ragisterAHB1enb;
unsigned int day;


int main(void)
{
	registerAHB1enb = (unsigned int *)RCC_AHB1ENR;




	*registerAHB1enb |= (1<<2);
    /* Loop forever */
	while(1){
		day++;
	}
}
